spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/user-db
    username: testuser
    password: testuser

  jpa:
    show-sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://idp-keycloak:8091/realms/microservices-realm

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

product:
  service:
    url: http://product-service:8081/products/

logging:
  level:
    root: INFO
