spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/user-db
    username: testuser
    password: testuser

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://idp-keycloak:8091/realms/microservices-realm

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${HOSTNAME:${random.value}}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# -------------------------------
# Logging
# -------------------------------
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE